troop_bar:
  type: rect
  left: 0.0
  top: 0.8056
  right: 1.0
  bottom: 1.0

# 英雄的框的所在区域， X1, Y1 = 140, 900      # 左上角像素坐标， X2, Y2 = 255, 1000  # 右下角像素坐标
hero:
  type: rect
  left: 0.0729
  top: 0.8333
  right: 0.1328
  bottom: 0.9259

night_witch:
  type: rect
  left: 0.1578
  top: 0.8657
  right: 0.2214
  bottom: 0.9204

deployment_zone:
  type: rect
  left: 0.3385
  top: 0.6296
  right: 0.3542
  bottom: 0.6389

# X1, Y1 = 400, 600    # 左上角像素坐标   X2, Y2 = 500, 666  # 右下角像素坐标
deployment_zone_2:
  type: rect
  left: 0.2083
  top: 0.5556
  right: 0.2604
  bottom: 0.6167

# X1, Y1 = 750, 450      # 左上角像素坐标   X2, Y2 = 1000, 530  # 右下角像素坐标
deployment_zone_3:
  type: rect
  left: 0.3906
  top: 0.4167
  right: 0.5208
  bottom: 0.4907

# X1, Y1 = 1040, 200      # 左上角像素坐标   X2, Y2 = 1250, 300  # 右下角像素坐标
deployment_zone_4:
  type: rect
  left: 0.5417
  top: 0.1852
  right: 0.651
  bottom: 0.2778

# 夜市界战斗过程中，左下角红色的投降按钮。
surrender_button:
  type: rect
  left: 0.0208
  top: 0.6667
  right: 0.125
  bottom: 0.7222
